name: 'Create calendar from  issues'
description: 'Creates an iCal file from issues that follow a specific template'
inputs:
  domain:
    description: "Domain"
    required: true
  company:
    description: "Company"
    required: true
  name:
    description: "Name"
    required: true
  timezone:
    description: "Timezone"
    default: 'US/Pacific'
  repository:
    description: "Repository"
    required: true
  file:
    description: "File"
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'